module.exports = {
  mtaxes: '/managementdashboard/accounts/taxes',
  mcurrencies: '/managementdashboard/accounts/currencies',
  minactiveaccounts: '/managementdashboard/accounts/inactiveaccounts',
  maccounts: '/managementdashboard/accounts/accounts',
  mlockedseries: '/managementdashboard/publications/locked-series',
  mpublishedseries: '/managementdashboard/publications/published-series',
  minterestbearingaccounts: '/managementdashboard/accounts/interestbearingaccounts',
  mjournals: '/managementdashboard/accounts/journals',
  mledgers: '/managementdashboard/accounts/ledgers',
  mworkbooks: '/managementdashboard/accounts/workbooks',
  massets: '/managementdashboard/accounts/assets',
  maccountants: '/managementdashboard/users/accountants',
  madmins: '/managementdashboard/users/admins',
  mauthors: '/managementdashboard/users/authors',
  mcustomers: '/managementdashboard/users/customers',
  meditors: '/managementdashboard/users/editors',
  moperators: '/managementdashboard/users/operators',
  msalesrepresantatives: '/managementdashboard/users/salesrepresantatives',
  email: '/app/pages/email',
  profile: '/app/pages/user-profile',
  calendar: '/app/pages/calendar',
  twitter: '#',
  github: '#',
  pinterest: '#',
  linkedin: '#',
  buy: '#',
};
