# Generated by Django 4.0.2 on 2022-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=16)),
                ('category', models.CharField(choices=[('REPAIR', 'REPAIR'), ('PRINTING', 'PRINTING'), ('PHOTOCOPYING', 'PHOTOCOPYING'), ('LAMINATING', 'LAMINATING')], max_length=200)),
                ('is_listed', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
