# Generated by Django 4.0.2 on 2022-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_is_listed_service_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
