
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICE = 'GET_SERVICE';
export const ADD_SERVICE = 'ADD_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const GET_SERVICE_IMAGES = 'GET_SERVICE_IMAGES';
export const ADD_SERVICE_IMAGE = 'ADD_SERVICE_IMAGE';
export const EDIT_SERVICE_IMAGE = 'EDIT_SERVICE_IMAGE';
