export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const GET_PRODUCT_IMAGES = 'GET_PRODUCT_IMAGES';
export const ADD_PRODUCT_IMAGE = 'ADD_PRODUCT_IMAGE';
export const EDIT_PRODUCT_IMAGE = 'EDIT_PRODUCT_IMAGE';