export const GET_PAYMENTS = 'GET_PAYMENTS';
export const GET_PAYMENT = 'GET_PAYMENT';
export const ADD_PAYMENT = 'ADD_PAYMENT';

export const GET_QUOTATIONS = 'GET_QUOTATIONS';
export const ADD_QUOTATION = 'ADD_QUOTATION';
export const EDIT_QUOTATION = 'EDIT_QUOTATION';
export const GET_QUOTATION = 'GET_QUOTATION';

export const GET_INVOICES = 'GET_INVOICES';
export const GET_INVOICE = 'GET_INVOICE';
export const ADD_INVOICE = 'ADD_INVOICE';

export const GET_INVOICE_LINES = 'GET_INVOICE_LINES';


export const PAY = 'PAY';
export const MAKE_INVOICE = 'MAKE_INVOICE';

export const GET_PAYMENT_REPORTS = 'GET_PAYMENT_REPORTS';

// export const GET_PAYMENTS = 'GET_PAYMENTS';
// export const GET_PAYMENT = 'GET_PAYMENT';
// export const ADD_PAYMENT = 'ADD_PAYMENT';

export const GET_CUSTOMER_PRODUCT_LINES = 'GET_CUSTOMER_PRODUCT_LINES';
export const ADD_CUSTOMER_PRODUCT_LINE = 'ADD_CUSTOMER_PRODUCT_LINE';
export const GET_CUSTOMER_PRODUCT_LINE = 'GET_CUSTOMER_PRODUCT_LINE';

export const GET_CUSTOMER_SERVICE_LINES = 'GET_CUSTOMER_SERVICE_LINES';
export const ADD_CUSTOMER_SERVICE_LINE = 'ADD_CUSTOMER_SERVICE_LINE';
export const GET_CUSTOMER_SERVICE_LINE = 'GET_CUSTOMER_SERVICE_LINE';

export const GET_CUSTOMER_INVOICES = "GET_CUSTOMER_INVOICES";
export const GET_CUSTOMER_INVOICE = "GET_CUSTOMER_INVOICE";
export const GET_CUSTOMER_QUOTATIONS = "GET_CUSTOMER_QUOTATIONS";
export const GET_CUSTOMER_QUOTATION = "GET_CUSTOMER_QUOTATION";

export const ACCEPT_INVOICE = "ACCEPT_INVOICE";
export const REJECT_INVOICE = "REJECT_INVOICE";
export const GET_CUSTOMER_PAYMENTS = "GET_CUSTOMER_PAYMENTS";
export const GET_CUSTOMER_CART = "GET_CUSTOMER_CART";
