export const ACTIVATE_USER_START = 'ACTIVATE_USER_START';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS ';
export const ACTIVATE_USER_FAIL = 'ACTIVATE_USER_FAIL';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS ';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
