# Generated by Django 4.0.2 on 2022-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='type',
            field=models.CharField(choices=[('PRODUCTS', 'PRODUCTS'), ('SERVICES', 'SERVICES')], default=None, max_length=255, null=True),
        ),
    ]
