# Generated by Django 4.0.2 on 2022-02-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoiceline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
