# Generated by Django 4.0.2 on 2022-02-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('art', 'art'), ('automative', 'automative'), ('computer', 'computer'), ('electronic', 'electronic'), ('fashion', 'fashion'), ('industrial_and_scientific', 'industrial_and_scientific'), ('video_game', 'video_game')], max_length=200, null=True)),
                ('visibility', models.CharField(choices=[('visible', 'VISIBLE'), ('invisible', 'INVISIBLE'), ('deleted', 'DELETED')], max_length=200)),
                ('return_policy', models.CharField(choices=[('returnable', 'This Item is returnable'), ('unreturnable', 'This item is not returnable')], max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
                ('digital', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
